spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/?(?<segment>.*), /api/v1/payment/$\{segment}

server:
  port: 8585
eureka:
  instance:
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
