spring:
  application:
    name: PAYMENT-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: localhost
server:
  port: ${PAYMENT_PORT:8080}
